using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace XpaConverterMvp;

internal static partial class ProjectGenerator
{
    private static string BuildSnippetSource(string rawSnippetCode, string generatedClassName)
    {
        return BuildSnippetSource(rawSnippetCode, generatedClassName, BuildSnippetNamespace(generatedClassName));
    }

    private static string BuildSnippetSource(string rawSnippetCode, string generatedClassName, string generatedNamespace)
    {
        var code = rawSnippetCode.Replace("\r\n", "\n").Replace('\r', '\n').Trim() + "\n";
        if (TryBuildSnippetSyntaxGapSource(code, generatedClassName, generatedNamespace, out var gapSource))
            return gapSource;

        code = Regex.Replace(
            code,
            @"(\b(?:public\s+|internal\s+)?(?:static\s+)?class\s+)Snippet\b",
            "$1" + generatedClassName,
            RegexOptions.IgnoreCase);
        if (Regex.IsMatch(code, @"(?m)^\s*namespace\b"))
            return code;

        var lines = code.Split('\n');
        var usingBlock = new List<string>();
        var bodyBlock = new List<string>();
        var inBody = false;
        foreach (var line in lines)
        {
            var trimmed = line.TrimStart();
            var isUsing = trimmed.StartsWith("using ", StringComparison.Ordinal);
            if (!inBody && (isUsing || string.IsNullOrWhiteSpace(line)))
            {
                usingBlock.Add(line.TrimEnd());
                continue;
            }

            inBody = true;
            bodyBlock.Add(line.TrimEnd());
        }

        var sb = new StringBuilder();
        foreach (var line in usingBlock)
            sb.AppendLine(line);
        if (usingBlock.Count > 0)
            sb.AppendLine();
        sb.AppendLine($"namespace {generatedNamespace}");
        sb.AppendLine("{");
        foreach (var line in bodyBlock)
            sb.AppendLine(line.Length == 0 ? "" : "    " + line);
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static bool TryBuildSnippetSyntaxGapSource(string code, string generatedClassName, string generatedNamespace, out string source)
    {
        source = "";
        if (!HasKnownSnippetSyntaxBlocker(code))
            return false;

        var methodMatch = Regex.Match(
            code,
            @"\bpublic\s+static\s+(?<return>[A-Za-z_][A-Za-z0-9_<>,\.\[\]\?]*)\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*\((?<params>[^)]*)\)",
            RegexOptions.CultureInvariant);
        if (!methodMatch.Success)
            return false;

        var returnType = methodMatch.Groups["return"].Value;
        var methodName = methodMatch.Groups["name"].Value;
        var parameters = methodMatch.Groups["params"].Value.Trim();
        var parsedParameters = SplitSnippetParameters(parameters)
            .Select(ParseSnippetParameter)
            .Where(p => p.Name.Length > 0)
            .ToList();

        var usingLines = code.Split('\n')
            .Select(l => l.Trim())
            .Where(l => Regex.IsMatch(l, @"^using\s+.+;\s*$", RegexOptions.CultureInvariant))
            .Distinct(StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        foreach (var line in usingLines)
            sb.AppendLine(line);
        if (usingLines.Count > 0)
            sb.AppendLine();
        sb.AppendLine($"namespace {generatedNamespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static class {generatedClassName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        public static {returnType} {methodName}({parameters})");
        sb.AppendLine("        {");
        sb.AppendLine("            // GAP: original XPA snippet contains invalid C# and was not emitted.");
        sb.AppendLine($"            System.Diagnostics.Debug.WriteLine(\"GAP: Snippet {Escape(generatedClassName)}.{Escape(methodName)} contains invalid C# and was not emitted.\");");
        foreach (var parameter in parsedParameters.Where(p => string.Equals(p.Modifier, "out", StringComparison.Ordinal)))
            sb.AppendLine($"            {parameter.Name} = default({parameter.Type});");
        if (!string.Equals(returnType, "void", StringComparison.OrdinalIgnoreCase))
            sb.AppendLine($"            return default({returnType});");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        source = sb.ToString();
        return true;
    }

    private static bool HasKnownSnippetSyntaxBlocker(string code)
    {
        return Regex.IsMatch(
            code,
            @"=\s*(?:\n\s*)+if\s*\(",
            RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
    }

    private readonly record struct SnippetParameter(string Modifier, string Type, string Name);

    private static IEnumerable<string> SplitSnippetParameters(string parameters)
    {
        if (string.IsNullOrWhiteSpace(parameters))
            yield break;

        var start = 0;
        var depth = 0;
        for (var i = 0; i < parameters.Length; i++)
        {
            var ch = parameters[i];
            if (ch == '<')
            {
                depth++;
                continue;
            }
            if (ch == '>' && depth > 0)
            {
                depth--;
                continue;
            }
            if (ch == ',' && depth == 0)
            {
                var part = parameters.Substring(start, i - start).Trim();
                if (part.Length > 0)
                    yield return part;
                start = i + 1;
            }
        }

        var last = parameters.Substring(start).Trim();
        if (last.Length > 0)
            yield return last;
    }

    private static SnippetParameter ParseSnippetParameter(string parameter)
    {
        var normalized = Regex.Replace(parameter.Trim(), @"\s+", " ");
        if (normalized.Length == 0)
            return new SnippetParameter("", "", "");

        var modifier = "";
        foreach (var candidate in new[] { "ref ", "out ", "in ", "params " })
        {
            if (!normalized.StartsWith(candidate, StringComparison.Ordinal))
                continue;

            modifier = candidate.Trim();
            normalized = normalized.Substring(candidate.Length).TrimStart();
            break;
        }

        var lastSpace = normalized.LastIndexOf(' ');
        if (lastSpace <= 0 || lastSpace >= normalized.Length - 1)
            return new SnippetParameter(modifier, "", "");

        var type = normalized.Substring(0, lastSpace).Trim();
        var name = normalized.Substring(lastSpace + 1).Trim().TrimStart('@');
        return new SnippetParameter(modifier, type, name);
    }

    private static string BuildSnippetNamespace(string generatedClassName)
        => $"GeneratedSnippets.{generatedClassName}Impl";

    private static bool RequiresFlowUsing(TaskSemantic t)
    {
        return t.DataView.TabCalls.Count > 0
            || t.FlowValidations.Count > 0
            || t.Logic.RowLogics.Any(r => r.Actions.Any(a => a.Call?.OperationType == "T"))
            || HasExpandBeforeFlow(t);
    }

    private static bool HasMergeLayoutInTree(TaskSemantic t, IReadOnlyList<TaskSemantic> allTasks)
    {
        if (HasMergeLayout(t))
            return true;
        return GetChildTasks(t.Ordinal, allTasks).Any(x => HasMergeLayoutInTree(x, allTasks));
    }
}

