using System.IO;
using System.Text;

namespace XpaConverterMvp;

internal static partial class ProjectGenerator
{
    private static void WriteProgramEntry(string outputRoot, string appNamespace)
    {
        var appName = string.IsNullOrWhiteSpace(appNamespace) ? "Application" : appNamespace.Split('.').First();
        var sb = new StringBuilder();
        sb.AppendLine("using XPARuntimeCore.Box;");
        sb.AppendLine($"namespace {appNamespace};");
        sb.AppendLine();
        sb.AppendLine("public class Program");
        sb.AppendLine("{");
        sb.AppendLine("    [System.STAThread]");
        sb.AppendLine("    public static void Main(string[] args)");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            var runtimeArgs = args ?? System.Array.Empty<string>();");
        sb.AppendLine("            var startProgram = ExtractStartProgram(ref runtimeArgs);");
        sb.AppendLine("            var runtimeParameters = ExtractRuntimeParameters(ref runtimeArgs);");
        sb.AppendLine("            Init(runtimeArgs);");
        sb.AppendLine("            ApplyRuntimeParameters(runtimeParameters);");
        sb.AppendLine("            Application.Run(startProgram);");
        sb.AppendLine("            ENV.UserSettings.FinalizeINI();");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (System.Exception e)");
        sb.AppendLine("        {");
        sb.AppendLine("            ENV.ErrorLog.WriteToLogFile(e, \"TOTAL CRASH\");");
        sb.AppendLine("            System.Environment.ExitCode = 1;");
        sb.AppendLine("            ENV.Common.ShowExceptionDialog(e);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static void Init(string[] args)");
        sb.AppendLine("    {");
        sb.AppendLine("        System.Windows.Forms.Application.EnableVisualStyles();");
        sb.AppendLine("        System.Windows.Forms.Application.SetCompatibleTextRenderingDefault(false);");
        sb.AppendLine("        ENV.Data.TextColumn.DefaultUseBackslashToDistinguishWildcards = true;");
        sb.AppendLine("        ENV.Data.DataProvider.XmlEntityDataProvider.SaveAnsiAsUTF8 = true;");
        sb.AppendLine("        ENV.UserSettings.Version10Compatible = true;");
        sb.AppendLine("        ENV.UserSettings.VersionXpaCompatible = true;");
        sb.AppendLine("        ENV.Data.ByteArrayColumn.UseAnsiForBinaryUnicode = false;");
        sb.AppendLine("        ENV.MenuManager.AllowEnabledHiddenMenuItems = true;");
        sb.AppendLine("        ENV.AbstractUIController.SuppressInputValidationOfFocusedControlWhenClosingByClickOnParentAndRowHasNotChanged = true;");
        sb.AppendLine("        ENV.BackwardCompatible.NullBehaviour.EqualToNullReturnsNull = false;");
        sb.AppendLine("        ENV.Data.DateColumn.GlobalDefault = new Date(1901,1,1);");
        sb.AppendLine("        ENV.Commands.SetDefaultKeyboardMapping();");
        sb.AppendLine("        ENV.Commands.SetVersion10CompatibleKeyMapping();");
        sb.AppendLine($"        ENV.Common.ApplicationTitle = \"{Escape(appName)}\";");
        sb.AppendLine("        ENV.AbstractUIController.UndoChangesInRowRevertsControllerState = true;");
        sb.AppendLine("        ENV.Data.DataProvider.SQLiteEntityDataProvider.AddToConnectionManager();");
        sb.AppendLine($"        ENV.UserSettings.InitUserSettings(\"{Escape(appName)}.ini\", args);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    static string ExtractStartProgram(ref string[] args)");
        sb.AppendLine("    {");
        sb.AppendLine("        string startProgram = null;");
        sb.AppendLine("        var runtimeArgs = new System.Collections.Generic.List<string>();");
        sb.AppendLine("        for (var index = 0; index < args.Length; index++)");
        sb.AppendLine("        {");
        sb.AppendLine("            var argument = args[index] ?? string.Empty;");
        sb.AppendLine("            if ((string.Equals(argument, \"--program\", System.StringComparison.OrdinalIgnoreCase) ||");
        sb.AppendLine("                 string.Equals(argument, \"/program\", System.StringComparison.OrdinalIgnoreCase)) &&");
        sb.AppendLine("                index + 1 < args.Length)");
        sb.AppendLine("            {");
        sb.AppendLine("                startProgram = args[++index];");
        sb.AppendLine("                continue;");
        sb.AppendLine("            }");
        sb.AppendLine("            if (argument.StartsWith(\"--program=\", System.StringComparison.OrdinalIgnoreCase) ||");
        sb.AppendLine("                argument.StartsWith(\"/program=\", System.StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine("            {");
        sb.AppendLine("                startProgram = argument.Substring(argument.IndexOf('=') + 1);");
        sb.AppendLine("                continue;");
        sb.AppendLine("            }");
        sb.AppendLine("            runtimeArgs.Add(argument);");
        sb.AppendLine("        }");
        sb.AppendLine("        args = runtimeArgs.ToArray();");
        sb.AppendLine("        return string.IsNullOrWhiteSpace(startProgram) ? null : startProgram.Trim();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    static System.Collections.Generic.Dictionary<string, string> ExtractRuntimeParameters(ref string[] args)");
        sb.AppendLine("    {");
        sb.AppendLine("        var parameters = new System.Collections.Generic.Dictionary<string, string>(System.StringComparer.OrdinalIgnoreCase);");
        sb.AppendLine("        var runtimeArgs = new System.Collections.Generic.List<string>();");
        sb.AppendLine("        for (var index = 0; index < args.Length; index++)");
        sb.AppendLine("        {");
        sb.AppendLine("            var argument = args[index] ?? string.Empty;");
        sb.AppendLine("            string definition = null;");
        sb.AppendLine("            if ((string.Equals(argument, \"--xpa-param\", System.StringComparison.OrdinalIgnoreCase) ||");
        sb.AppendLine("                 string.Equals(argument, \"/xpa-param\", System.StringComparison.OrdinalIgnoreCase)) &&");
        sb.AppendLine("                index + 1 < args.Length)");
        sb.AppendLine("            {");
        sb.AppendLine("                definition = args[++index];");
        sb.AppendLine("            }");
        sb.AppendLine("            else if (argument.StartsWith(\"--xpa-param=\", System.StringComparison.OrdinalIgnoreCase) ||");
        sb.AppendLine("                     argument.StartsWith(\"/xpa-param=\", System.StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine("            {");
        sb.AppendLine("                definition = argument.Substring(argument.IndexOf('=') + 1);");
        sb.AppendLine("            }");
        sb.AppendLine("            else");
        sb.AppendLine("            {");
        sb.AppendLine("                runtimeArgs.Add(argument);");
        sb.AppendLine("                continue;");
        sb.AppendLine("            }");
        sb.AppendLine("            var separator = (definition ?? string.Empty).IndexOf('=');");
        sb.AppendLine("            if (separator > 0)");
        sb.AppendLine("            {");
        sb.AppendLine("                var name = definition.Substring(0, separator).Trim();");
        sb.AppendLine("                if (name.Length > 0)");
        sb.AppendLine("                    parameters[name] = definition.Substring(separator + 1);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        args = runtimeArgs.ToArray();");
        sb.AppendLine("        return parameters;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    static void ApplyRuntimeParameters(System.Collections.Generic.Dictionary<string, string> parameters)");
        sb.AppendLine("    {");
        sb.AppendLine("        foreach (var parameter in parameters)");
        sb.AppendLine("            ENV.UserMethods.Instance.SetParam(parameter.Key, parameter.Value);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        WriteGeneratedSourceFile(outputRoot, "Program", sb.ToString());
    }

}

