using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace XpaConverterMvp;

internal static partial class ProjectGenerator
{
    private const string AutoGeneratedHeader = "// <auto-generated />";

    private static string GeneratedSourceFileName(string sourceName)
        => $"{sourceName}.cs";

    private static void WriteGeneratedSourceFile(string targetDir, string sourceName, string code, Encoding? encoding = null)
    {
        Directory.CreateDirectory(targetDir);
        File.WriteAllText(
            Path.Combine(targetDir, GeneratedSourceFileName(sourceName)),
            EnsureAutoGeneratedHeader(code),
            encoding ?? Encoding.UTF8);
    }

    private static string EnsureAutoGeneratedHeader(string code)
    {
        if (code.StartsWith(AutoGeneratedHeader, StringComparison.Ordinal))
            return code;

        return AutoGeneratedHeader + Environment.NewLine + code;
    }

    private static string PostProcessGeneratedTaskCode(string code)
    {
        return code;
    }

    private static string ResolveTaskOutputFolder(string? rawFolder)
    {
        if (string.IsNullOrWhiteSpace(rawFolder))
            return string.Empty;

        var folder = rawFolder.Trim();
        if (Regex.IsMatch(folder, @"^_\d+_[A-Za-z0-9_]+$"))
            return folder;
        var numbered = Regex.Match(folder, @"^\s*(\d+)\s*\.\s*(.+)$");
        if (numbered.Success)
            return "_" + numbered.Groups[1].Value + "_" + ToPascalIdentifier(numbered.Groups[2].Value);

        return ToPascalIdentifier(folder);
    }

    private static string ResolveEffectiveTaskOutputFolder(TaskSemantic task, IReadOnlyList<TaskSemantic> allTasks)
    {
        TaskSemantic? current = task;
        while (current is not null)
        {
            var folder = ResolveTaskOutputFolder(current.Folder);
            if (!string.IsNullOrWhiteSpace(folder))
                return folder;
            if (!current.ParentOrdinal.HasValue)
                break;
            current = allTasks.FirstOrDefault(t => t.Ordinal == current.ParentOrdinal.Value);
        }
        return string.Empty;
    }

    private static string QuoteTelemetry(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return "\"\"";

        return "\"" + value.Replace("\"", "\"\"") + "\"";
    }

    private static T TimeSection<T>(Func<T> action, string category, string owner, string section)
    {
        var stopwatch = Stopwatch.StartNew();
        try
        {
            return action();
        }
        finally
        {
            ConversionTelemetry.LogDuration(category, owner, stopwatch.Elapsed, $"section={QuoteTelemetry(section)}");
        }
    }

    private static void TimeSection(Action action, string category, string owner, string section)
    {
        var stopwatch = Stopwatch.StartNew();
        try
        {
            action();
        }
        finally
        {
            ConversionTelemetry.LogDuration(category, owner, stopwatch.Elapsed, $"section={QuoteTelemetry(section)}");
        }
    }

    private static void WriteTaskSnippetFiles(TaskSemantic rootTask, IReadOnlyList<TaskSemantic> allTasks, string targetDir)
    {
        var emitted = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var task in EnumerateTaskTree(rootTask, allTasks))
        {
            var snippetInvokes = EnumerateTaskInvokes(task)
                .Where(i => i.OperationType == "." && !string.IsNullOrWhiteSpace(i.SnippetCode) && !string.IsNullOrWhiteSpace(i.FunctionName))
                .ToList();
            if (snippetInvokes.Count == 0)
                continue;

            var classBase = ToTaskClassName(task.Description) + "Snippet";
            var suffix = 0;
            foreach (var invoke in snippetInvokes)
            {
                var className = suffix == 0 ? classBase : classBase + (suffix + 1).ToString();
                var code = BuildSnippetSource(invoke.SnippetCode!, className, BuildSnippetNamespace(className));
                while (emitted.TryGetValue(className, out var existing) && !string.Equals(existing, code, StringComparison.Ordinal))
                {
                    suffix++;
                    className = classBase + (suffix + 1).ToString();
                    code = BuildSnippetSource(invoke.SnippetCode!, className, BuildSnippetNamespace(className));
                }

                if (emitted.TryGetValue(className, out var same) && string.Equals(same, code, StringComparison.Ordinal))
                {
                    suffix++;
                    continue;
                }

                emitted[className] = code;
                WriteGeneratedSourceFile(targetDir, className, code);
                suffix++;
            }
        }
    }

    private static IEnumerable<TaskSemantic> EnumerateTaskTree(TaskSemantic rootTask, IReadOnlyList<TaskSemantic> allTasks)
    {
        yield return rootTask;
        var children = allTasks
            .Where(x => x.ParentOrdinal == rootTask.Ordinal)
            .OrderBy(x => x.SubtaskIndex ?? int.MaxValue);
        foreach (var child in children)
        {
            foreach (var nested in EnumerateTaskTree(child, allTasks))
                yield return nested;
        }
    }

    private static IEnumerable<TaskInvokeDef> EnumerateTaskInvokes(TaskSemantic task)
    {
        foreach (var h in task.HandlersSemantic.Items)
            foreach (var i in h.Invokes)
                yield return i;

        static IEnumerable<TaskInvokeDef> EnumerateRowActions(IEnumerable<TaskRowLogicDef> rows)
        {
            foreach (var r in rows)
            foreach (var a in r.Actions)
                if (a.Invoke is not null)
                    yield return a.Invoke;
        }

        foreach (var i in EnumerateRowActions(task.Logic.StartLogics))
            yield return i;
        foreach (var i in EnumerateRowActions(task.Logic.EndLogics))
            yield return i;
        foreach (var i in EnumerateRowActions(task.Logic.RowLogics))
            yield return i;
        foreach (var i in EnumerateRowActions(task.Logic.SavingRowLogics))
            yield return i;
        foreach (var g in task.Logic.GroupLogics)
        foreach (var a in g.Actions)
            if (a.Invoke is not null)
                yield return a.Invoke;

        foreach (var fn in task.FunctionOverridesSemantic)
        foreach (var a in fn.OrderedActions)
            if (a.Invoke is not null)
                yield return a.Invoke;
    }

}

