using System;
using System.IO;

namespace XpaConverterMvp;

internal static partial class ProjectGenerator
{
    private static void WriteEnterpriseServerCompatAsset(string outputRoot, string appNamespace)
    {
        var lines = new[]
        {
            $"global using static {appNamespace}.EnterpriseServerCompat;",
            "",
            "using System;",
            "using XPARuntimeCore.Box;",
            "",
            $"namespace {appNamespace};",
            "",
            "// Broker-only requester functions that do not currently exist in the .NET ENV runtime.",
            "// Generated under the SDD rules from local Magic xpa help + XML usage evidence.",
            "internal static class EnterpriseServerCompat",
            "{",
            "    [ENV.NotYetImplemented]",
            "    public static byte[] RqContexts(Text serviceName, Text queryPassword) => Array.Empty<byte>();",
            "",
            "    [ENV.NotYetImplemented]",
            "    public static Text RqCtxInf(Text serviceName, Text contextId, Text queryPassword) => \"\";",
            "",
            "    [ENV.NotYetImplemented]",
            "    public static Bool RqCtxTrm(Text serviceName, Number contextEntryNumber, Text supervisorPassword) => false;",
            "",
            "    [ENV.NotYetImplemented]",
            "    public static Bool RqRtBlock(Text serviceName, Number entryNumber, Text supervisorPassword, Bool allRequests) => false;",
            "",
            "    [ENV.NotYetImplemented]",
            "    public static Bool RqRtBlock(Text serviceName, Number entryNumber, Text supervisorPassword, Bool allRequests, Bool shutdown) => false;",
            "",
            "    [ENV.NotYetImplemented]",
            "    public static Text RqRtCtx(Text serviceName, Number contextEntryNumber) => \"\";",
            "",
            "    [ENV.NotYetImplemented]",
            "    public static Number RqRtCtxs(Text serviceName, Number runtimeEngineNumber) => 0;",
            "",
            "    [ENV.NotYetImplemented]",
            "    public static Number RqTrmTimeout() => 0;",
            "",
            "    [ENV.NotYetImplemented]",
            "    public static Bool RqHTTPStatusCode(Number statusCode, Text reasonPhrase) => false;",
            "}",
            ""
        };
        File.WriteAllText(Path.Combine(outputRoot, "EnterpriseServerCompat.cs"), string.Join(Environment.NewLine, lines));
    }

    private static void WriteXmlCompatAsset(string outputRoot, string appNamespace)
    {
        var lines = new[]
        {
            "using System;",
            "using System.Xml;",
            "using ENV;",
            "using XPARuntimeCore.Box;",
            "",
            $"namespace {appNamespace};",
            "",
            "// Generated under the SDD rules from XML + local Magic xpa help + ENV XML runtime evidence.",
            "internal static class XmlCompat",
            "{",
            "    public static byte[] XMLBlobGet(Number generation, Number ioIndex, Text path)",
            "    {",
            "        return UserMethods.Instance.XMLBlobGet(generation, ioIndex, path);",
            "    }",
            "",
            "    public static byte[] XMLBlobGet(Number generation, Number ioIndex, Text path, Text attributeName)",
            "    {",
            "        return UserMethods.Instance.XMLBlobGet(generation, ioIndex, path, attributeName);",
            "    }",
            "",
            "    public static byte[] XMLBlobGet(Number generation, Number ioIndex, Text path, Text attributeName, Bool checkExists)",
            "    {",
            "        var useAttribute = !string.IsNullOrWhiteSpace((attributeName ?? \"\").ToString());",
            "        var exists = useAttribute",
            "            ? UserMethods.Instance.XMLExist(generation, ioIndex, path, attributeName)",
            "            : UserMethods.Instance.XMLExist(generation, ioIndex, path);",
            "        if (!exists && checkExists)",
            "            return null;",
            "        return useAttribute",
            "            ? UserMethods.Instance.XMLBlobGet(generation, ioIndex, path, attributeName)",
            "            : UserMethods.Instance.XMLBlobGet(generation, ioIndex, path);",
            "    }",
            "",
            "    public static Text DbXmlMixedGet(Type entityType, Text path, Text element)",
            "    {",
            "        try",
            "        {",
            "            if (Activator.CreateInstance(entityType) is not ENV.Data.Entity entity)",
            "                return \"\";",
            "            var fileName = entity.EntityName;",
            "            if (string.IsNullOrWhiteSpace(fileName) || !System.IO.File.Exists(fileName))",
            "                return \"\";",
            "            var doc = new XmlDocument();",
            "            doc.Load(fileName);",
            "            var target = doc.SelectSingleNode((path ?? \"\").ToString());",
            "            if (target == null)",
            "                return \"\";",
            "            var marker = (element ?? \"\").ToString().Trim();",
            "            var returnNextText = string.IsNullOrEmpty(marker);",
            "            foreach (XmlNode child in target.ChildNodes)",
            "            {",
            "                if (returnNextText && (child.NodeType == XmlNodeType.Text || child.NodeType == XmlNodeType.CDATA))",
            "                    return child.InnerText ?? \"\";",
            "                if (child.NodeType == XmlNodeType.Element && string.Equals(child.LocalName, marker, StringComparison.OrdinalIgnoreCase))",
            "                    returnNextText = true;",
            "            }",
            "        }",
            "        catch",
            "        {",
            "        }",
            "        return \"\";",
            "    }",
            "}",
            ""
        };
        File.WriteAllText(Path.Combine(outputRoot, "XmlCompat.cs"), string.Join(Environment.NewLine, lines));
    }

    private static void WriteJavaCompatAsset(string outputRoot, string appNamespace)
    {
        var lines = new[]
        {
            "using System;",
            "using System.Collections;",
            "using System.Reflection;",
            "using ENV;",
            "using ENV.Data;",
            "using ENV.Java;",
            "using XPARuntimeCore.Box;",
            "",
            $"namespace {appNamespace};",
            "",
            "// Generated under the SDD rules from XML + local Magic xpa help + ENV Java runtime evidence.",
            "internal static class JavaCompat",
            "{",
            "    static readonly BindingFlags All = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static;",
            "",
            "    public static object JGetStatic(Text classAndFieldName, Text signature)",
            "    {",
            "        try",
            "        {",
            "            using var jni = new JavaNativeInterface();",
            "            var env = (JavaInvoker)GetPrivateField(jni, \"env\");",
            "            SplitStaticFieldName(classAndFieldName, out var className, out var fieldName);",
            "            var clazz = env.FindClass(className.Replace(\".\", \"/\"));",
            "            var fieldId = env.GetStaticFieldID(clazz, fieldName, signature);",
            "            return ReadStaticField(env, clazz, fieldId, signature);",
            "        }",
            "        catch",
            "        {",
            "            return null;",
            "        }",
            "    }",
            "",
            "    public static Bool JSetStatic(Text classAndFieldName, Text signature, object value)",
            "    {",
            "        try",
            "        {",
            "            using var jni = new JavaNativeInterface();",
            "            var env = (JavaInvoker)GetPrivateField(jni, \"env\");",
            "            SplitStaticFieldName(classAndFieldName, out var className, out var fieldName);",
            "            var clazz = env.FindClass(className.Replace(\".\", \"/\"));",
            "            var fieldId = env.GetStaticFieldID(clazz, fieldName, signature);",
            "            return WriteStaticField(env, clazz, fieldId, signature, UnboxMagicValue(value));",
            "        }",
            "        catch",
            "        {",
            "            return false;",
            "        }",
            "    }",
            "",
            "    public static Bool JSet(ByteArrayColumn objReference, Text fieldName, Text signature, object value)",
            "    {",
            "        try",
            "        {",
            "            var jni = GetContextJavaObject(objReference);",
            "            var env = (JavaInvoker)GetPrivateField(jni, \"env\");",
            "            var javaClass = (IntPtr)GetPrivateField(jni, \"javaClass\");",
            "            var javaObject = (IntPtr)GetPrivateField(jni, \"javaObject\");",
            "            var fieldId = env.GetFieldID(javaClass, fieldName, signature);",
            "            return WriteInstanceField(env, javaObject, fieldId, signature, UnboxMagicValue(value));",
            "        }",
            "        catch",
            "        {",
            "            return false;",
            "        }",
            "    }",
            "",
            "    public static Bool JInstanceOf(ByteArrayColumn objReference, Text className)",
            "    {",
            "        try",
            "        {",
            "            var jni = GetContextJavaObject(objReference);",
            "            var env = (JavaInvoker)GetPrivateField(jni, \"env\");",
            "            var javaObject = (IntPtr)GetPrivateField(jni, \"javaObject\");",
            "            var objectClass = (IntPtr)InvokeNonPublicResult(env, \"GetObjectClass\", javaObject);",
            "            var targetClass = env.FindClass(className.ToString().Replace(\".\", \"/\"));",
            "            var classClass = env.FindClass(\"java/lang/Class\");",
            "            var isAssignableFrom = env.GetMethodId(classClass, \"isAssignableFrom\", \"(Ljava/lang/Class;)Z\");",
            "            return env.CallBooleanMethod(targetClass, isAssignableFrom, new JValue { l = objectClass });",
            "        }",
            "        catch",
            "        {",
            "            return false;",
            "        }",
            "    }",
            "",
            "    static JavaNativeInterface GetContextJavaObject(ByteArrayColumn objReference)",
            "    {",
            "        if (objReference?.Value == null || objReference.Value.Length != 16)",
            "            throw new InvalidOperationException(\"Java pseudo-reference is empty.\");",
            "",
            "        var field = typeof(UserMethods).GetField(\"_javaObjects\", All);",
            "        var contextStatic = field.GetValue(null);",
            "        var valueProperty = contextStatic.GetType().GetProperty(\"Value\", All);",
            "        var dictionary = (IDictionary)valueProperty.GetValue(contextStatic);",
            "        var guid = new Guid(objReference.Value);",
            "        var jni = dictionary[guid] as JavaNativeInterface;",
            "        if (jni == null)",
            "            throw new InvalidOperationException(\"Java pseudo-reference is not part of the current context.\");",
            "        return jni;",
            "    }",
            "",
            "    static object GetPrivateField(object instance, string fieldName)",
            "    {",
            "        var field = instance.GetType().GetField(fieldName, All);",
            "        if (field == null)",
            "            throw new MissingFieldException(instance.GetType().FullName, fieldName);",
            "        return field.GetValue(instance);",
            "    }",
            "",
            "    static void SplitStaticFieldName(Text classAndFieldName, out string className, out string fieldName)",
            "    {",
            "        var fullName = classAndFieldName.ToString();",
            "        var lastDot = fullName.LastIndexOf('.');",
            "        if (lastDot <= 0 || lastDot >= fullName.Length - 1)",
            "            throw new ArgumentException(\"Expected class.field name\", nameof(classAndFieldName));",
            "        className = fullName.Substring(0, lastDot);",
            "        fieldName = fullName.Substring(lastDot + 1);",
            "    }",
            "",
            "    static object ReadStaticField(JavaInvoker env, IntPtr clazz, IntPtr fieldId, string signature)",
            "    {",
            "        switch ((signature ?? string.Empty).Trim())",
            "        {",
            "            case \"I\": return env.GetStaticIntField(clazz, fieldId);",
            "            case \"Z\": return env.GetStaticBooleanField(clazz, fieldId);",
            "            case \"B\": return env.GetStaticByteField(clazz, fieldId);",
            "            case \"S\": return env.GetStaticShortField(clazz, fieldId);",
            "            case \"J\": return env.GetStaticLongField(clazz, fieldId);",
            "            case \"F\": return env.GetStaticFloatField(clazz, fieldId);",
            "            case \"D\": return env.GetStaticDoubleField(clazz, fieldId);",
            "            case \"C\": return env.GetStaticCharField(clazz, fieldId);",
            "            case \"Ljava/lang/String;\":",
            "                var strHandle = env.GetStaticObjectField(clazz, fieldId);",
            "                return strHandle == IntPtr.Zero ? string.Empty : (string)InvokeNonPublicResult(env, \"JStringToString\", strHandle);",
            "            default:",
            "                return env.GetStaticObjectField(clazz, fieldId);",
            "        }",
            "    }",
            "",
            "    static Bool WriteStaticField(JavaInvoker env, IntPtr clazz, IntPtr fieldId, string signature, object value)",
            "    {",
            "        switch ((signature ?? string.Empty).Trim())",
            "        {",
            "            case \"I\": InvokeNonPublic(env, \"SetStaticIntField\", clazz, fieldId, Convert.ToInt32(value)); return true;",
            "            case \"Z\": InvokeNonPublic(env, \"SetStaticBooleanField\", clazz, fieldId, Convert.ToBoolean(value)); return true;",
            "            case \"B\": InvokeNonPublic(env, \"SetStaticByteField\", clazz, fieldId, Convert.ToByte(value)); return true;",
            "            case \"S\": InvokeNonPublic(env, \"SetStaticShortField\", clazz, fieldId, Convert.ToInt16(value)); return true;",
            "            case \"J\": InvokeNonPublic(env, \"SetStaticLongField\", clazz, fieldId, Convert.ToInt64(value)); return true;",
            "            case \"F\": InvokeNonPublic(env, \"SetStaticFloatField\", clazz, fieldId, Convert.ToSingle(value)); return true;",
            "            case \"D\": InvokeNonPublic(env, \"SetStaticDoubleField\", clazz, fieldId, Convert.ToDouble(value)); return true;",
            "            case \"C\": InvokeNonPublic(env, \"SetStaticCharField\", clazz, fieldId, Convert.ToChar(value)); return true;",
            "            case \"Ljava/lang/String;\":",
            "                var text = value?.ToString() ?? string.Empty;",
            "                var handle = env.NewString(text, text.Length);",
            "                InvokeNonPublic(env, \"SetStaticObjectField\", clazz, fieldId, handle);",
            "                return true;",
            "            default:",
            "                return false;",
            "        }",
            "    }",
            "",
            "    static Bool WriteInstanceField(JavaInvoker env, IntPtr javaObject, IntPtr fieldId, string signature, object value)",
            "    {",
            "        switch ((signature ?? string.Empty).Trim())",
            "        {",
            "            case \"I\": InvokeNonPublic(env, \"SetIntField\", javaObject, fieldId, Convert.ToInt32(value)); return true;",
            "            case \"Z\": InvokeNonPublic(env, \"SetBooleanField\", javaObject, fieldId, Convert.ToBoolean(value)); return true;",
            "            case \"B\": InvokeNonPublic(env, \"SetByteField\", javaObject, fieldId, Convert.ToByte(value)); return true;",
            "            case \"S\": InvokeNonPublic(env, \"SetShortField\", javaObject, fieldId, Convert.ToInt16(value)); return true;",
            "            case \"J\": InvokeNonPublic(env, \"SetLongField\", javaObject, fieldId, Convert.ToInt64(value)); return true;",
            "            case \"F\": InvokeNonPublic(env, \"SetFloatField\", javaObject, fieldId, Convert.ToSingle(value)); return true;",
            "            case \"D\": InvokeNonPublic(env, \"SetDoubleField\", javaObject, fieldId, Convert.ToDouble(value)); return true;",
            "            case \"C\": InvokeNonPublic(env, \"SetCharField\", javaObject, fieldId, Convert.ToChar(value)); return true;",
            "            case \"Ljava/lang/String;\":",
            "                var text = value?.ToString() ?? string.Empty;",
            "                var handle = env.NewString(text, text.Length);",
            "                InvokeNonPublic(env, \"SetObjectField\", javaObject, fieldId, handle);",
            "                return true;",
            "            default:",
            "                return false;",
            "        }",
            "    }",
            "",
            "    static object UnboxMagicValue(object value)",
            "    {",
            "        if (value == null)",
            "            return null;",
            "        var valueProperty = value.GetType().GetProperty(\"Value\", All);",
            "        if (valueProperty != null && valueProperty.GetIndexParameters().Length == 0)",
            "            return valueProperty.GetValue(value);",
            "        return value;",
            "    }",
            "",
            "    static void InvokeNonPublic(object instance, string methodName, params object[] args)",
            "    {",
            "        var method = instance.GetType().GetMethod(methodName, All);",
            "        if (method == null)",
            "            throw new MissingMethodException(instance.GetType().FullName, methodName);",
            "        method.Invoke(instance, args);",
            "    }",
            "",
            "    static object InvokeNonPublicResult(object instance, string methodName, params object[] args)",
            "    {",
            "        var method = instance.GetType().GetMethod(methodName, All);",
            "        if (method == null)",
            "            throw new MissingMethodException(instance.GetType().FullName, methodName);",
            "        return method.Invoke(instance, args);",
            "    }",
            "}",
            ""
        };
        File.WriteAllText(Path.Combine(outputRoot, "JavaCompat.cs"), string.Join(Environment.NewLine, lines));
    }
}

